---
abstract: 'Yet Another HTTP Dispatcher'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  HTTP::Request: 0
  Test::MockObject: 0
  Test::More: 0
  Test::use::ok: 0
  URI: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Router
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  MooseX::AttributeHelpers: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
